# Site settings
title: DIEGO NEVES FARIA
email: diegonevesfaria@gmail.com
description: >-
  Um desenvolvedor Full Stack com especialização em infraestrutura e que ama tecnologias novas que nos auxiliam em nossa vida. Atualmente virando um
  Nômade Digital e desenvolvendo APIs e criando Apps Mobile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: pt-BR

permalink: /artigo/:title/
paginate: 2
paginate_path: "/pagina/:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
